# Generated by Django 3.0.8 on 2020-07-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='rodada',
            field=models.IntegerField(default=0),
        ),
    ]
