# Generated by Django 3.0.8 on 2020-07-03 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0005_auto_20200703_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='rodada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partida', to='jogos.Rodada'),
        ),
    ]
